// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiguelGuedelha.Umbraco.RedirectsManager.Persistence.EFCore;

#nullable disable

namespace MiguelGuedelha.Umbraco.RedirectsManager.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(RedirectsManagerDbContext))]
    partial class RedirectsManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("MiguelGuedelha.Umbraco.RedirectsManager.Persistence.EFCore.Models.Redirects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("Culture")
                        .HasColumnType("TEXT")
                        .HasColumnName("culture");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("destinationId");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("destinationType");

                    b.Property<string>("DestinationUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("destinationUrl");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isPermanent");

                    b.Property<bool>("IsRegex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isRegex");

                    b.Property<string>("OriginUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("originUrl");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("TEXT")
                        .HasColumnName("siteId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("RedirectsManager", null, t =>
                        {
                            t.HasCheckConstraint("CK_OneDestinationSet", "(destinationId IS NOT NULL AND (destinationUrl IS NULL OR destinationUrl = '')) \nOR \n(destinationId IS NULL AND (destinationUrl IS NOT NULL AND destinationUrl <> ''))");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
