// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiguelGuedelha.Umbraco.RedirectsManager.Persistence.EFCore;

#nullable disable

namespace MiguelGuedelha.Umbraco.RedirectsManager.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(RedirectsManagerDbContext))]
    [Migration("20260214120756_Initial Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiguelGuedelha.Umbraco.RedirectsManager.Persistence.EFCore.Models.Redirects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Culture")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("culture");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int")
                        .HasColumnName("destinationId");

                    b.Property<Guid?>("DestinationKey")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("destinationKey");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("destinationType");

                    b.Property<string>("DestinationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("destinationUrl");

                    b.Property<bool>("ForwardQuery")
                        .HasColumnType("bit")
                        .HasColumnName("forwardQuery");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("bit")
                        .HasColumnName("isPermanent");

                    b.Property<bool>("IsRegex")
                        .HasColumnType("bit")
                        .HasColumnName("isRegex");

                    b.Property<string>("OriginUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("originUrl");

                    b.Property<string>("Query")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("query");

                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-1)
                        .HasColumnName("siteId");

                    b.Property<Guid>("SiteKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("siteKey");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("SiteId", "OriginUrl")
                        .IsUnique();

                    b.ToTable("redirectsManager", null, t =>
                        {
                            t.HasCheckConstraint("CK_GlobalOrScopedSiteSet", "(\r\n    siteId = -1 \r\n    AND\r\n    siteKey = '00000000-0000-0000-0000-000000000000'\r\n)\r\nOR\r\n(\r\n    siteId > -1 \r\n    AND \r\n    siteKey <> '00000000-0000-0000-0000-000000000000'\r\n)");

                            t.HasCheckConstraint("CK_OneDestinationSet", "(\r\n    destinationId IS NOT NULL \r\n    AND \r\n    (\r\n        destinationUrl IS NULL \r\n        OR \r\n        destinationUrl = ''\r\n    )\r\n) \r\nOR \r\n(\r\n    destinationId IS NULL \r\n    AND \r\n    (\r\n        destinationUrl IS NOT NULL \r\n        AND \r\n        destinationUrl <> ''\r\n    )\r\n)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
