// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiguelGuedelha.Umbraco.RedirectsManager.Persistence.EFCore;

#nullable disable

namespace MiguelGuedelha.Umbraco.RedirectsManager.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(RedirectsManagerDbContext))]
    [Migration("20260209183835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiguelGuedelha.Umbraco.RedirectsManager.Persistence.EFCore.Models.Redirects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("culture");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("destinationId");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("destinationType");

                    b.Property<string>("DestinationUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("destinationUrl");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("bit")
                        .HasColumnName("isPermanent");

                    b.Property<bool>("IsRegex")
                        .HasColumnType("bit")
                        .HasColumnName("isRegex");

                    b.Property<string>("OriginUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("originUrl");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("siteId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("RedirectsManager", null, t =>
                        {
                            t.HasCheckConstraint("CK_OneDestinationSet", "(destinationId IS NOT NULL AND (destinationUrl IS NULL OR destinationUrl = '')) \nOR \n(destinationId IS NULL AND (destinationUrl IS NOT NULL AND destinationUrl <> ''))");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
